export const OPEN_NOTIFY = 'OPEN_NOTIFY';
export const CLOSE_NOTIFY = 'CLOSE_NOTIFY';
export const SUCCESS_NOTIFY = 'SUCCESS_NOTIFY';
export const ERROR_NOTIFY = 'ERROR_NOTIFY';
export const WARNING_NOTIFY = 'WARNING_NOTIFY';
export const INFO_NOTIFY = 'INFO_NOTIFY';